export const quizData = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris", "Rome"],
    correctAnswer: "Paris",
    difficulty: "easy",
    timer: 20,
  },
  {
    id: 2,
    question:
      "Which one of the following river flows between Vindhyan and Satpura ranges?",
    options: ["Narmada", "Mahanandi", "Son", "Netravati"],
    correctAnswer: "Narmada",
    difficulty: "medium",
    timer: 20,
  },
  {
    id: 3,
    question: "How many tags are in a regular HTML element?",
    options: ["2", "1", "3", "4"],
    correctAnswer: "2",
    difficulty: "easy",
    timer: 20,
  },
  {
    id: 4,
    question: "<br/ > What type of tag is this?",
    options: ["Break tag", "Broken tag", "An opening tag", "none of this"],
    correctAnswer: "Break tag",
    difficulty: "medium",
    timer: 20,
  },
  {
    id: 5,
    question: "What is the smallest header in HTML by default?",
    options: ["h1", "h2", "h3", "h6"],
    correctAnswer: "h6",
    difficulty: "medium",
    timer: 20,
  },
  {
    id: 6,
    question: "Who wrote 'Romeo and Juliet'?",
    options: [
      "Jane Austen",
      "William Shakespeare",
      "Charles Dickens",
      "Leo Tolstoy",
    ],
    correctAnswer: "William Shakespeare",
    difficulty: "medium",
    timer: 20,
  },
  {
    id: 7,
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondrion", "Endoplasmic Reticulum"],
    correctAnswer: "Mitochondrion",
    difficulty: "easy",
    timer: 20,
  },
  {
    id: 8,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "NaCl", "O2"],
    correctAnswer: "H2O",
    difficulty: "hard",
    timer: 20,
  },
  {
    id: 9,
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctAnswer: "Mars",
    difficulty: "medium",
    timer: 20,
  },
  {
    id: 10,
    question: "Who is the author of 'To Kill a Mockingbird'?",
    options: [
      "Harper Lee",
      "J.K. Rowling",
      "Mark Twain",
      "F. Scott Fitzgerald",
    ],
    correctAnswer: "Harper Lee",
    difficulty: "hard",
    timer: 20,
  },
];

export const points = {
  easy: 1,
  medium: 2,
  hard: 3,
};
